// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
// 
// Custom CS PostProcessing Shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/SceneCapturePixelShader.usf"

// Shader parameters


Texture2D OriginalSceneColor;
Texture2D VelocityFluid;
Texture2D PreviousFrame;
Texture2D Velocity;
Texture2D DatamoshCanvas;
Texture2D CustomDepth;
Texture2D SceneDepth;
Texture2D<uint2> CustomStencil;

SamplerState DepthBufferSampler;

// SceneColor Viewport parameters
SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)

SCREEN_PASS_TEXTURE_VIEWPORT(SceneVelocityViewport)
SCREEN_PASS_TEXTURE_VIEWPORT(CustomDepthStencilViewport)
SCREEN_PASS_TEXTURE_VIEWPORT(SceneDepthViewport)

// Outputs

RWTexture2D<float4> Output;

RWTexture2D<float4> DatamoshCanvasOutput;

RWTexture2D<float4> VelocityFluidOutput;

uint FullScreenDatamosh;

const float RandomOffsetMultiplier = 100.;

float4 GaussianSample(
	const Texture2D Texture,
	const float2 ScreenSize,
	const float2 UvMin,
	const float2 UvMax,
	const float2 UvCenter
)
{
	const float Guassian_Kernel[9] = {
		1.0 / 16, 2.0 / 16, 1.0 / 16,
		2.0 / 16, 4.0 / 16, 2.0 / 16,
		1.0 / 16, 2.0 / 16, 1.0 / 16
	};

	const uint GaussianKernelSize = 9;

	const float2 Offset = float2(1., 1.) / ScreenSize;

	const float2 Offsets[9] = {
		float2(-Offset.x, Offset.y), // top-left
		float2(0.0f, Offset.y), // top-center
		float2(Offset.x, Offset.y), // top-right
		float2(-Offset.x, 0.0f), // center-left
		float2(0.0f, 0.0f), // center-center
		float2(Offset.x, 0.0f), // center-right
		float2(-Offset.x, -Offset.y), // bottom-left
		float2(0.0f, -Offset.y), // bottom-center
		float2(Offset.x, -Offset.y) // bottom-right
	};


	float4 GuassianSample = float4(0., 0., 0., 0.);

	for (uint i = 0; i < GaussianKernelSize; i++)
	{
		float2 Uv = clamp(UvCenter + Offsets[i], UvMin, UvMax);
		GuassianSample += Texture.SampleLevel(GlobalPointClampedSampler, Uv, 0) * Guassian_Kernel[i];
	}

	return GuassianSample;
}

float2 InterpretSceneVelocity(float2 Uv, float2 ViewportUV, float Depth)
{
	const float4 Sampled = Velocity.SampleLevel(GlobalPointClampedSampler, Uv, 0);

	float2 FragmentVelocity = length2(Sampled.xy) == 0. ? Sampled.xy : DecodeVelocityFromTexture(Sampled).xy;

	// This engine is made by illiterate psychopaths
	FragmentVelocity.y *= -1;

	// float2 ScreenSize = View.ViewSize.xy;
	const float2 ScreenSize = SceneColorViewport_ViewportSize;
	const float AspectRatio = ScreenSize.x / ScreenSize.y;

	FragmentVelocity.y /= AspectRatio;
	// FragmentVelocity.x *= AspectRatio;

	// FragmentVelocity *= ScreenSize;
	// FragmentVelocity = round(FragmentVelocity) * SceneColorViewport_ViewportSizeInverse;
	// FragmentVelocity /= ScreenSize;

	return FragmentVelocity;
}

float4 SampleDatamoshCanvas(float2 Uv)
{
	float4 Color;
	float2 ClampedUv = clamp(Uv, SceneColorViewport_UVViewportMin, SceneColorViewport_UVViewportMax);

	if (any(Uv > SceneColorViewport_UVViewportMax) || any(Uv < SceneColorViewport_ViewportMin))
	{
		Color = OriginalSceneColor.SampleLevel(
			GlobalPointClampedSampler,
			Uv + (Uv - ClampedUv),
			0
		);
	}
	else
	{
		Color = DatamoshCanvas.SampleLevel(
			GlobalPointClampedSampler,
			ClampedUv,
			0
		);
	}


	return Color;
}


// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	// Check that we are in scope
	if (any(DispatchThreadId >= SceneColorViewport_ViewportMax))
	{
		return;
	}

	const uint2 SceneWriteIndex = DispatchThreadId + SceneColorViewport_ViewportMin;

	// Calculate SampleUV with viewport parameters
	const float2 SceneColorUV = (float2(SceneColorViewport_ViewportMin) + (DispatchThreadId + 0.5)) *
		SceneColorViewport_ExtentInverse;

	const float2 SceneDepthUV =
		(SceneColorUV - SceneColorViewport_UVViewportMin)
		* SceneColorViewport_UVViewportSizeInverse
		* SceneDepthViewport_UVViewportSize
		+ SceneDepthViewport_UVViewportMin;

	const float2 CustomDepthUV =
		(SceneColorUV - SceneColorViewport_UVViewportMin)
		* SceneColorViewport_UVViewportSizeInverse
		* CustomDepthStencilViewport_UVViewportSize
		+ CustomDepthStencilViewport_UVViewportMin;

	const float2 FragmentVelocityUV =
		(SceneColorUV - SceneColorViewport_UVViewportMin)
		* SceneColorViewport_UVViewportSizeInverse
		* SceneVelocityViewport_UVViewportSize
		+ SceneVelocityViewport_UVViewportMin;

	const float4 OriginalColor = OriginalSceneColor.SampleLevel(GlobalPointClampedSampler, SceneColorUV, 0);

	const float FragmentDepth = SceneDepth.SampleLevel(DepthBufferSampler, SceneDepthUV, 0).r;

	const float4 FragmentCustomDepth = CustomDepth.SampleLevel(DepthBufferSampler, CustomDepthUV, 0);

	const float2 ScreenSpaceVelocity = InterpretSceneVelocity(FragmentVelocityUV, SceneColorUV, FragmentDepth.r);

	float2 FluidVelocity = VelocityFluid.SampleLevel(GlobalPointClampedSampler, SceneColorUV + ScreenSpaceVelocity, 0).
	                                     xy;

	if (length2(ScreenSpaceVelocity) > 0.0)
	{
		FluidVelocity.xy += ScreenSpaceVelocity.xy;
	}
	else
	{
	}
	FluidVelocity.xy *= 0.9;

	float2 FluidOutput = FluidVelocity.xy;

	float2 Offset = -ScreenSpaceVelocity;


	Offset +=
		((round((float2(RandFast(DispatchThreadId + uint2(100. * SceneColorUV)),
		                RandFast(DispatchThreadId * 2 + uint2(100. * SceneColorUV))))) * 5.f / 5.f -
			0.5f))
		* (RandomOffsetMultiplier * 0.01 * length(ScreenSpaceVelocity));

	float2 CanvasOffsetUV = SceneColorUV + Offset;

	// float4 CanvasFragment = DatamoshCanvas.SampleLevel(
	// 	GlobalPointClampedSampler,
	// 	CanvasOffsetUV,
	// 	1
	// );
	float4 CanvasFragment = SampleDatamoshCanvas(CanvasOffsetUV);
	// float4 CanvasFragment = GaussianSample(
	// 	DatamoshCanvas,
	// 	SceneColorViewport_ViewportSize,
	// 	SceneColorViewport_UVViewportMin,
	// 	SceneColorViewport_UVViewportMax,
	// 	CanvasOffsetUV
	// );

	// CanvasFragment.rgb += 1. * float3(252., 3., 132.) / 255. * lengthFast(float3(ScreenSpaceVelocity, 0.))
	// 	* clamp(1. - FragmentDepth, 0., 1.);
	// CanvasFragment.r += 0.001;

	float4 SceneOutput = OriginalColor;

	if ((FragmentCustomDepth.r > 0. && FragmentDepth <= FragmentCustomDepth.r) || FullScreenDatamosh != 0)
	{
		SceneOutput = CanvasFragment;
	}
	// SceneOutput = CanvasFragment;

	Output[SceneWriteIndex] = SceneOutput;
	DatamoshCanvasOutput[SceneWriteIndex] = SceneOutput;
	VelocityFluidOutput[SceneWriteIndex] = float4(FluidOutput, 0., 1.);
}
