// Custom SceneViewExtension Template for Unreal Engine
// Copyright 2023 - 2025 Ossi Luoto
// 
// Custom CS PostProcessing Shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"
#include "/Engine/Private/SceneCapturePixelShader.usf"

// Shader parameters


// SceneColor texture
Texture2D OriginalSceneColor;
Texture2D VelocityFluid;
Texture2D PreviousFrame;
Texture2D Velocity;
Texture2D DatamoshCanvas;
Texture2D CustomDepth;
Texture2D<uint2> CustomStencil;

SamplerState DepthBufferSampler;

// SceneColor Viewport parameters
SCREEN_PASS_TEXTURE_VIEWPORT(SceneColorViewport)

SCREEN_PASS_TEXTURE_VIEWPORT(SceneVelocityViewport)
SCREEN_PASS_TEXTURE_VIEWPORT(CustomDepthStencilViewport)

// Outputs

RWTexture2D<float4> Output;

RWTexture2D<float4> DatamoshCanvasOutput;

RWTexture2D<float4> VelocityFluidOutput;


float4 GaussianSample(
	const Texture2D Texture,
	const float2 ScreenSize,
	const float2 UvMin,
	const float2 UvMax,
	const float2 UvCenter
)
{
	const float Guassian_Kernel[9] = {
		1.0 / 16, 2.0 / 16, 1.0 / 16,
		2.0 / 16, 4.0 / 16, 2.0 / 16,
		1.0 / 16, 2.0 / 16, 1.0 / 16
	};

	const uint GaussianKernelSize = 9;

	const float2 Offset = float2(1., 1.) / ScreenSize;

	const float2 Offsets[9] = {
		float2(-Offset.x, Offset.y), // top-left
		float2(0.0f, Offset.y), // top-center
		float2(Offset.x, Offset.y), // top-right
		float2(-Offset.x, 0.0f), // center-left
		float2(0.0f, 0.0f), // center-center
		float2(Offset.x, 0.0f), // center-right
		float2(-Offset.x, -Offset.y), // bottom-left
		float2(0.0f, -Offset.y), // bottom-center
		float2(Offset.x, -Offset.y) // bottom-right
	};


	float4 GuassianSample = float4(0., 0., 0., 0.);

	for (uint i = 0; i < GaussianKernelSize; i++)
	{
		float2 Uv = clamp(UvCenter + Offsets[i], UvMin, UvMax);
		GuassianSample += Texture.SampleLevel(GlobalPointClampedSampler, Uv, 0) * Guassian_Kernel[i];
	}

	return GuassianSample;
}

float4 BoxSample(
	const Texture2D Texture,
	const float2 ScreenSize,
	const float2 UvMin,
	const float2 UvMax,
	const float2 UvCenter
)
{
	const uint BoxKernelSize = 7;

	const float2 Offset = float2(1., 1.) / ScreenSize;

	float4 Sample = float4(0., 0., 0., 0.);

	for (uint x = 0; x < BoxKernelSize; x++)
	{
		for (uint y = 0; y < BoxKernelSize; y++)
		{
			float2 Uv = clamp(UvCenter + float2(x, y) * Offset, UvMin, UvMax);
			Sample += Texture.SampleLevel(GlobalPointClampedSampler, Uv, 0);
		}
	}

	Sample /= float(BoxKernelSize * BoxKernelSize);

	return Sample;
}

// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	// Check that we are in scope
	if (any(DispatchThreadId >= SceneColorViewport_ViewportMax))
	{
		return;
	}

	const uint2 SceneWriteIndex = DispatchThreadId + SceneColorViewport_ViewportMin;

	const float2 SceneColorCutoutViewportSize = SceneColorViewport_ViewportSize;

	// Calculate SampleUV with viewport parameters
	const float2 SceneColorUV =
		(float2(SceneColorViewport_ViewportMin) + (DispatchThreadId + 0.5)) * SceneColorViewport_ExtentInverse;

	const float2 VelocityUV =
		SceneColorUV * (SceneVelocityViewport_UVViewportMax - SceneVelocityViewport_UVViewportMin) +
		SceneVelocityViewport_UVViewportMin;


	const float4 FragmentVelocityEncoded = Velocity.SampleLevel(GlobalPointClampedSampler, VelocityUV, 0);
	float3 FragmentVelocity = float3(0., 0., 0.);

	if (length2(FragmentVelocityEncoded) > 0.)
	{
		FragmentVelocity = DecodeVelocityFromTexture(FragmentVelocityEncoded);
	}

	float2 FluidVelocityAtPoint = VelocityFluid.SampleLevel(
		GlobalPointClampedSampler,
		SceneColorUV,
		0
	).xy;

	const float2 VelocityFluidUVOffset =
		clamp(SceneColorUV - FluidVelocityAtPoint, SceneColorViewport_UVViewportMin,
		      SceneColorViewport_UVViewportMax);

	// FluidVelocityAtPoint = VelocityFluid.SampleLevel(
	// 	GlobalPointClampedSampler,
	// 	VelocityFluidUVOffset,
	// 	0
	// ).xy;

	FluidVelocityAtPoint = BoxSample(
		VelocityFluid,
		SceneColorCutoutViewportSize,
		SceneColorViewport_UVViewportMin,
		SceneColorViewport_UVViewportMax,
		VelocityFluidUVOffset
	).xy;


	FluidVelocityAtPoint *= 0.99;
	FluidVelocityAtPoint += FragmentVelocity.xy;

	// FluidVelocityAtPoint = normalize(FluidVelocityAtPoint) * min(length(FluidVelocityAtPoint), 1.f);
	FluidVelocityAtPoint += min((length(FluidVelocityAtPoint)), 0.1) *
		normalize(float2(FluidVelocityAtPoint.y, -FluidVelocityAtPoint.x));

	if (isnan(FluidVelocityAtPoint.x) || isnan(FluidVelocityAtPoint.y))
	{
		FluidVelocityAtPoint = float2(0., 0.);
	}

	const float2 Offset = FluidVelocityAtPoint / SceneColorCutoutViewportSize * 5. * 5.;
	// const float2 Offset = -lerp(FragmentVelocity.xy, FluidVelocityAtPoint, 0.01);
	// const float2 Offset = FragmentVelocity.xy;
	// const float2 Offset = FluidVelocityAtPoint.xy;


	const float4 OriginalColor = OriginalSceneColor.SampleLevel(
		GlobalPointClampedSampler,
		clamp(SceneColorUV, SceneColorViewport_UVViewportMin, SceneColorViewport_UVViewportMax),
		0
	);

	const float4 CanvasFragment = DatamoshCanvas.SampleLevel(
		GlobalPointClampedSampler,
		clamp(SceneColorUV - Offset,
		      SceneColorViewport_UVViewportMin,
		      SceneColorViewport_UVViewportMax),
		0
	);

	// const float2 CustomrepthStencilUV =
	// 	(SceneColorUV - SceneColorViewport_UVViewportMin) / (SceneColorViewport_UVViewportMax -
	// 		SceneColorViewport_UVViewportMin) * (CustomDepthStencilViewport_UVViewportMax -
	// 		CustomDepthStencilViewport_UVViewportMin) +
	// 	CustomDepthStencilViewport_UVViewportMin;


	float2 CustomDepthStencilUV;

	CustomDepthStencilUV =
		SceneColorUV * (CustomDepthStencilViewport_UVViewportMax - CustomDepthStencilViewport_UVViewportMin) +
		CustomDepthStencilViewport_UVViewportMin;

	// CustomDepthStencilUV = float2(SceneColorUV);

	bool swap = any(CustomDepthStencilViewport_ViewportSize < SceneColorViewport_ViewportSize);
	if (swap)
	{
		// CustomDepthStencilUV /= abs(SceneColorCutoutViewportSize - CustomDepthStencilViewport_ViewportSize);
	}
	// CustomDepthStencilUV /= max(float2(CustomDepthStencilViewport_ViewportSize), SceneColorViewport_ViewportSize);
	// CustomDepthStencilUV /= CustomDepthStencilViewport_ViewportSize * SceneColorViewport_ViewportSizeInverse;
	// CustomDepthStencilUV *= float2(1., 0.785);

	// const float4 DepthStencil = CustomDepth.SampleLevel(
	// 	DepthBufferSampler,
	// 	CustomDepthStencilUV,
	// 	0
	// );
	// const float4 DepthStencil = CustomDepth.Load(
	// 	uint3(
	// 		(SceneColorUV) / (SceneColorViewport_UVViewportMax - SceneColorViewport_UVViewportMin) *
	// 		float2(CustomDepthStencilViewport_ViewportMax - CustomDepthStencilViewport_ViewportMin) +
	// 		CustomDepthStencilViewport_ViewportMin, 0)
	// );
	const float4 DepthStencil = CustomDepth.Load(
		uint3(float2(CustomDepthStencilUV) * CustomDepthStencilViewport_Extent,
		      0)
	);

	const uint2 Stencil = CustomStencil.Load(uint3(
		float2(CustomDepthStencilUV) * CustomDepthStencilViewport_Extent, 0
	));
	// const uint2 Stencil = CustomStencil.SampleLevel(DepthBufferSampler, CustomDepthStencilUV, 0);


	const float4 CanvasOutput = CanvasFragment;

	// float4 SceneOutput = lerp(OriginalColor, CanvasOutput,
	//                           clamp(distance(float2(0.5, 0.5), SceneUVNormalized) * 6., 0., 1.));
	float4 SceneOutput = OriginalColor;

	// if ((Stencil.r) != 0)
	if (DepthStencil.r > 0)
	{
		SceneOutput = CanvasOutput;
		// SceneOutput = float4(swap ? 0. : 1., 0., 1., 1.);
	}

	if (any(CustomDepthStencilUV > CustomDepthStencilViewport_UVViewportMax) || any(
		CustomDepthStencilUV < CustomDepthStencilViewport_UVViewportMin))
	{
		SceneOutput = float4(0., 0., 0., 1.);
	}

	// SceneOutput.rg = length(CustomDepthStencilUV);
	// SceneOutput.b = DepthStencil.r;
	// SceneOutput.r = round(length(FragmentVelocity) * 100.) / 50.;

	DatamoshCanvasOutput[SceneWriteIndex] = SceneOutput;
	Output[SceneWriteIndex] = SceneOutput;
	VelocityFluidOutput[SceneWriteIndex] = float4(FluidVelocityAtPoint, 0, 1);

	// if (Stencil == 0)
	// {
	// 	Output[SceneWriteIndex] = float4(0., 0., 0., 1.);
	// }
	// Output[SceneWriteIndex] = DepthStencil;
}
